package id.majopay.gateway.ui.theme

import androidx.compose.ui.graphics.Color

// Notification Sync System — Light palette
val SyncPrimary = Color(0xFF004AC6)
val SyncOnPrimary = Color(0xFFFFFFFF)
val SyncPrimaryContainer = Color(0xFFDBE1FF)
val SyncOnPrimaryContainer = Color(0xFF00174B)
val SyncSecondary = Color(0xFF516070)
val SyncOnSecondary = Color(0xFFFFFFFF)
val SyncSecondaryContainer = Color(0xFFD5E4F8)
val SyncOnSecondaryContainer = Color(0xFF3A4858)
val SyncTertiary = Color(0xFF4E565B)
val SyncOnTertiary = Color(0xFFFFFFFF)
val SyncTertiaryContainer = Color(0xFFDBE4EA)
val SyncOnTertiaryContainer = Color(0xFF3F484D)
val SyncError = Color(0xFFBA1A1A)
val SyncOnError = Color(0xFFFFFFFF)
val SyncErrorContainer = Color(0xFFFFDAD6)
val SyncOnErrorContainer = Color(0xFF93000A)
val SyncBackground = Color(0xFFF9F9FF)
val SyncOnBackground = Color(0xFF111C2D)
val SyncSurface = Color(0xFFF9F9FF)
val SyncOnSurface = Color(0xFF111C2D)
val SyncSurfaceVariant = Color(0xFFD8E3FB)
val SyncOnSurfaceVariant = Color(0xFF434655)
val SyncOutline = Color(0xFF737686)
val SyncOutlineVariant = Color(0xFFC3C6D7)
val SyncSurfaceContainerLowest = Color(0xFFFFFFFF)
val SyncSurfaceContainerLow = Color(0xFFF0F3FF)
val SyncSurfaceContainer = Color(0xFFE7EEFF)
val SyncSurfaceContainerHigh = Color(0xFFDEE8FF)
val SyncSurfaceContainerHighest = Color(0xFFD8E3FB)
val SyncInverseSurface = Color(0xFF263143)
val SyncInverseOnSurface = Color(0xFFECF1FF)
val SyncInversePrimary = Color(0xFFB4C5FF)

// Dark palette (derived from same hue family)
val SyncDarkPrimary = Color(0xFFB4C5FF)
val SyncDarkOnPrimary = Color(0xFF00174B)
val SyncDarkPrimaryContainer = Color(0xFF003EA8)
val SyncDarkOnPrimaryContainer = Color(0xFFDBE1FF)
val SyncDarkSecondary = Color(0xFFB9C8DB)
val SyncDarkOnSecondary = Color(0xFF233141)
val SyncDarkSecondaryContainer = Color(0xFF3A4858)
val SyncDarkOnSecondaryContainer = Color(0xFFD5E4F8)
val SyncDarkBackground = Color(0xFF0F1419)
val SyncDarkOnBackground = Color(0xFFE2E2E9)
val SyncDarkSurface = Color(0xFF0F1419)
val SyncDarkOnSurface = Color(0xFFE2E2E9)
val SyncDarkSurfaceVariant = Color(0xFF263143)
val SyncDarkOnSurfaceVariant = Color(0xFFC3C6D7)
val SyncDarkOutline = Color(0xFF8D9199)
val SyncDarkOutlineVariant = Color(0xFF43474E)
val SyncDarkSurfaceContainerLowest = Color(0xFF090C12)
val SyncDarkSurfaceContainerLow = Color(0xFF181C22)
val SyncDarkSurfaceContainer = Color(0xFF1C2026)
val SyncDarkSurfaceContainerHigh = Color(0xFF272A30)
val SyncDarkSurfaceContainerHighest = Color(0xFF31353B)

// Status accents (semantic) — used directly when MaterialTheme cannot encode them
val SuccessGreen = Color(0xFF1E8E3E)
val SuccessGreenLight = Color(0xFFE6F4EA)
val WarningAmber = Color(0xFFB06000)
val WarningAmberLight = Color(0xFFFFF1D6)
val ErrorRed = Color(0xFFBA1A1A)
val ErrorRedLight = Color(0xFFFFDAD6)
val InfoBlue = Color(0xFF1967D2)
val InfoBlueLight = Color(0xFFD3E3FD)

// Gradient (subtle blue) — kept for legacy hero usages, value mirrors primary range
val GradientStart = Color(0xFF2563EB)
val GradientEnd = Color(0xFF004AC6)
